graph TD
    A[Créer le jeu] --> B[Choisir la méthode d'affichage]
    B --> C[Obtenir le fichier]
    C --> D[Extraire les données]
    D --> E{Données valides ?}
    E -->|Non| F[Gérer l'erreur de fichier]
    E -->|Oui| I[Créer la grille]
    I --> J[Stocker les données dans la grille]
    J --> K[Initialiser les cellules]
    
    K --> M{Grille valide ?}

    M -->|Non| O[Gérer l'erreur de la grille]
    M -->|Oui| N[Mettre à jour les cellules]
    N --> P[Notifier les observateurs]
    P --> Q[Choisir la sortie]
    Q --> R{Affichage graphique ?}
    R -->|Oui| T[Afficher en graphique]
    R -->|Non| U[Afficher en console]
    U --> V[Sauvegarder dans un fichier texte]
    U --> M

    O --> W[Fin]
    F --> W
    T --> M
    N -->Z[Incrémenter itérations]
    Z --> AA{<small>Nombre d'itérations atteint ?</small>}
    AA -->|Oui| W
    AA -->|Non| M

    M --> commentaire[<small><i>Vérifiez que le tableau n'est pas vide et qu'il différent du précédent.</i></small>]
    
