usecaseDiagram
    actor User as "Utilisateur"
    actor Admin as "Administrateur"

    usecase UC1 as "Afficher le menu"
    usecase UC2 as "Initialiser le jeu"
    usecase UC3 as "Jouer une partie"

    User --> UC1
    User --> UC2
    Admin --> UC3
